### ISSUE TITLE
NHCN codes from csv to mongo collecton

### ISSUE THREAD

**Issue by sohail0992** [codeforpakistan/HCAIs-Surveillance-Backend#8] opened 2022-01-12 08:50 UTC

**Comment by mubassirhayat** [comment] 2022-01-13 08:28
Duplicate of #7

**Closed by mubassirhayat** 2022-01-13 08:28 UTC

**Comment by mubassirhayat** [comment] 2022-01-21 09:23
These codes had ambiguity and so we are using just the ICD-10 Code for the procedures.
